# Numpy
## 1. numpy array
Существует 3 способа создания массива: \
    1) конвертация обычных списков \
    2) использование встроеных функций \
    3) создание случайных данных

In [2]:
import numpy as np

In [2]:
lst = [1, 2, 3]
type(lst)

list

In [3]:
arr = np.array(lst)
arr

array([1, 2, 3])

In [4]:
type(arr)

numpy.ndarray

In [5]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Shift + Tab = read manual

In [7]:
np.arange(2, 5, 1)

array([2, 3, 4])

In [8]:
# позволяет делать дробный шаг

np.arange(1, 2, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [3]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [5]:
np.full((2, 3), -1)

array([[-1, -1, -1],
       [-1, -1, -1]])

In [15]:
np.linspace(0, 10, 8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [16]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# создание единичной матрицы
np.eye(4, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# равномерное распределение [0, 1)
np.random.rand(2, 5)

array([[0.13068073, 0.97121615, 0.50383494, 0.80667089, 0.56590285],
       [0.35114333, 0.1332611 , 0.73913556, 0.15692187, 0.68154136]])

In [21]:
np.random.rand(6)

array([0.31206849, 0.17496295, 0.83755304, 0.66498142, 0.60424234,
       0.89379322])

In [ ]:
# стандартное нормальное распределение 
np.random.randn(5, 2, 2)

array([[[ 0.12527854,  0.11230353],
        [ 1.26603951, -0.36223187]],

       [[-0.97072217,  0.25586132],
        [ 1.25137537, -0.18375697]],

       [[-1.9538391 ,  1.27875114],
        [ 1.96489661, -0.37656641]],

       [[ 0.66067812,  1.81535138],
        [ 2.04883838,  0.09439639]],

       [[ 0.98115323,  0.46599305],
        [-1.24692664, -1.48047991]]])

In [25]:
# равномерное случайное распределение
np.random.randint(5, 100, 6)

array([77, 17, 90, 77, 58, 33])

In [27]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [33]:
arr = np.arange(0, 25, 1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
arr.reshape((5, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
arr.max()

24

In [36]:
arr.min()

0

In [ ]:
arr.argmax() # index

24

In [38]:
arr.argmin()

0

In [39]:
arr.dtype

dtype('int32')

In [40]:
arr.shape

(25,)

In [41]:
lst
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
from IPython.display import display

display(lst)
display(arr)

[1, 2, 3]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])