# Numpy
## Индексирование и среды 

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[5]

5

In [4]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [5]:
arr[:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[5:]

array([5, 6, 7, 8, 9])

In [8]:
# broadcast - применение функции ко всем элементам
arr[:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [9]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
new_arr = arr[:5]
new_arr

array([0, 1, 2, 3, 4])

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# срез дает ссылку на элементы исходного массива
new_arr[:3] = -1
new_arr

array([-1, -1, -1,  3,  4])

In [13]:
arr

array([-1, -1, -1,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr_copy = arr.copy()
arr_copy[:5] = 100

arr

array([-1, -1, -1,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
arr_2d[0][1]

10

In [18]:
arr_2d.shape

(3, 3)

In [19]:
arr_2d[0, 1]

10

In [22]:
arr_2d[:2, :2]

array([[ 5, 10],
       [20, 25]])

In [23]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [24]:
mask = arr > 4

arr[mask]

array([ 5,  6,  7,  8,  9, 10])

In [25]:
arr

array([-1, -1, -1,  3,  4,  5,  6,  7,  8,  9, 10])