# Numpy
## delete and add elemetns

In [2]:
import numpy as np

In [3]:
arr = np.arange(0, 9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
np.delete(arr, arr[2:4])

array([0, 1, 4, 5, 6, 7, 8])

In [7]:
arr = np.random.randint(0, 100, 10)

In [8]:
arr

array([72, 14, 54, 82, 90, 66, 81, 30, 15, 58])

In [9]:
np.delete(arr, [1, 5, 7])

array([72, 54, 82, 90, 81, 15, 58])

In [10]:
arr

array([72, 14, 54, 82, 90, 66, 81, 30, 15, 58])

In [12]:
np.append(arr, [-1])

array([72, 14, 54, 82, 90, 66, 81, 30, 15, 58, -1])

In [15]:
np.insert(arr, 4, 4)

array([72, 14, 54, 82,  4, 90, 66, 81, 30, 15, 58])